//Analog Gauges Calculation AND display

//FUEL LEVEL GAUGE:
//mainFuelLevel; //Calculate Gauge value of Fuel Level AND analog value FOR gauge on dashboard

//ENGINE TEMPERATURE GAUGE:
mainEngineTempGauge;

// SPEEDOMETER:
mainSpeedometer;

// ENGINE SPEED
mainEngineSpeed;

// FUEL LEVEL
mainFuelLevel;

// OIL PRESSURE
mainEngineOilPressure;

// TRANS OIL TEMPERATURE
mainTransOilTemperature;


