/* device:       /project/NMS_GUI */
/* device model: PC_Windows */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SCREENFRAME_CPP
#define INCLUDE__VT3_EVENT__SCREENFRAME_CPP

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__ScreenFrame.h"
#include "vt3_Event__ScreenFrame.h"
#include "vt3_extra.h"

/* define the names of the indicators */

/* define the names of the indicators */

/* timer event handler for screen frame: /project/NMS_GUI/screen_frame */
void vt3_event_ind_screen_frame(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/NMS_GUI/screen_frame
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: screen_frame */


#endif /* INCLUDE__VT3_EVENT__SCREENFRAME_CPP */

/* end of file */
