/* device:       /project/MC2M/CPU0 */
/* device model: MC2M_2CPU\CPU0 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_POU__CAN_CALLBACK_DM01_TCM_C
#define INCLUDE__VT3_POU__CAN_CALLBACK_DM01_TCM_C

#include "vt3_base.h"
#include "vt3_POU_common.h"
#include "vt3_extra.h"

#pragma CONST_SEG CSEG VT3_INIT
#pragma DATA_SEG DSEG BANKED_RAM


/* FUNCTION definition */
BOOL can_callback_DM01_TCM(UINT dlc, BYTE FARPTR data)
{
	/* local constants */

	/* local variables */
	BYTE lamp_command = ((BYTE)0x0U); /*  */
	/* end of local variables */

	/* body of code */
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/MC2M/CPU0/SubRoutines/TCM/AlarmManagement/MultiAlarm/can_callback_DM01_TCM
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	    
	    //ilk calismada dikkate alma   
	    if (!TCM_starting) {
	        
	//        DM1_Engine_decode.dlc = dlc;
	        DM01_TCM_decode.dlc = dlc;
	//        DM1_Engine_decode.data = data;
	        DM01_TCM_decode.data = data;
	//        DM1_Engine_decode__call();
	        DM01_TCM_decode__call();
	
	        if ((DM01_TCM_decode.DTC_COUNT == 1) &&
	            (TCM_MoreThanOneActiveFault)) {
	                ;
	        }
	        else {
	            //Amber Warning Lamp
	            //lamp_command = DM1_Engine_AmberWarningLamp * 4;
	            lamp_command = DM01_TCM_AmberWarningLamp * 4;
	            //lamp_command |= DM1_Engine_FlashAmberWarningLamp;
	            lamp_command |= DM01_TCM_FlashAmberWarningLamp;
	            TCM_led_AWL_Engine = lamp_command & 0x0F;
	        
	            //Red Stop Lamp
	            lamp_command *= 16; //left shift 4 bits
	            //lamp_command |= DM1_Engine_RedStopLamp * 4;
	            lamp_command |= DM01_TCM_RedStopLamp * 4;
	            //lamp_command |= DM1_Engine_FlashRedStopLamp;        
	            lamp_command |= DM01_TCM_FlashRedStopLamp;        
	            TCM_led_RSL_Engine = lamp_command & 0x0F;
	        
	            //Red Protection Lamp
	            lamp_command *= 16; //left shift 4 bits
	            //lamp_command |= DM1_Engine_ProtectLamp * 4;
	            lamp_command |= DM01_TCM_ProtectLamp * 4;
	            //lamp_command |= DM1_Engine_FlashProtectLamp;
	            lamp_command |= DM01_TCM_FlashProtectLamp;
	            TCM_led_RPL_Engine = lamp_command & 0x0F;
	        }
	    }
	    
	    return (TRUE);   
	}

	/* end of FUNCTION body */
} /* end of FUNCTION can_callback_DM01_TCM */

#pragma CONST_SEG DEFAULT
#pragma DATA_SEG DEFAULT

#endif /* INCLUDE__VT3_POU__CAN_CALLBACK_DM01_TCM_C */

/* end of file */
