/* device:       /project/MC2M/CPU0 */
/* device model: MC2M_2CPU\CPU0 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_POU__ACTIVATEWDO_C
#define INCLUDE__VT3_POU__ACTIVATEWDO_C

#include "vt3_base.h"
#include "vt3_POU_common.h"
#include "vt3_extra.h"

#pragma CONST_SEG CSEG VT3_INIT
#pragma DATA_SEG DSEG BANKED_RAM


/* initializers of addressed variables */

/* table of initializators of addressed variables */
static const vt3_screen_initializer FAR __init_table__ActivateWDO[] = {
	{ NULL, NULL, 0 } /* sentinel */
}; /* __init_table__ActivateWDO[] */

/* initializers of in_out parameters */

/* POU constants */
/* end of POU constants */

/* initialize values for POU status */
static const ActivateWDO_t FAR __const__ActivateWDO__param_init = 
{
	/* EN                   */ TRUE,
	/* ENO                  */ TRUE,
	/* WDO0                 */ TRUE,
	/* WDO1                 */ TRUE,
	/* WDO2                 */ TRUE,
	/* WDO3                 */ TRUE,
	/* WDO4                 */ TRUE,
}; /* end of __const__ActivateWDO__param_init */

/* initialization of PROGRAM status */
void ActivateWDO__init(void)
{
	const vt3_screen_initializer FARPTR p;

	/* initialize addressed variables */
	for ( p = __init_table__ActivateWDO; p->len; p ++ )
	{
		FarMemCopy(p->dst, p->src, p->len);
	}

	/* initialize local data */
	FarMemCopy(&ActivateWDO, &__const__ActivateWDO__param_init, sizeof __const__ActivateWDO__param_init);

	/* initialize function block instances */
}

/* PROGRAM execution */
void ActivateWDO__call(void)
{
	/* local variables */
	/* end of local variables */

	/* preamble: conditional execution */
	ActivateWDO.ENO = ActivateWDO.EN;
	if ( ! ActivateWDO.EN )
		return;


	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/MC2M/CPU0/LibraryFunctions/ActivateWDO
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	(void)SetWDO(0, (ActivateWDO.WDO0));
	(void)SetWDO(1, (ActivateWDO.WDO1));
	(void)SetWDO(2, (ActivateWDO.WDO2));
	(void)SetWDO(3, (ActivateWDO.WDO3));
	(void)SetWDO(4, (ActivateWDO.WDO4));
	
	}

	/* end of PROGRAM body */
}


#pragma CONST_SEG DEFAULT
#pragma DATA_SEG DEFAULT

#endif /* INCLUDE__VT3_POU__ACTIVATEWDO_C */

/* end of file */
