/* device:       /project/MC2M/CPU0 */
/* device model: MC2M_2CPU\CPU0 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_POU__EL_FORMAT_LOCAL2_C
#define INCLUDE__VT3_POU__EL_FORMAT_LOCAL2_C

#include "vt3_base.h"
#include "vt3_POU_common.h"
#include "vt3_extra.h"

#pragma CONST_SEG CSEG VT3_INIT
#pragma DATA_SEG DSEG BANKED_RAM


/* initializers of addressed variables */

/* table of initializators of addressed variables */
static const vt3_screen_initializer FAR __init_table__EL_format_local2[] = {
	{ NULL, NULL, 0 } /* sentinel */
}; /* __init_table__EL_format_local2[] */

/* initializers of in_out parameters */

/* POU constants */
/* end of POU constants */

/* initialize values for POU status */
static const EL_format_local2_t FAR __const__EL_format_local2__param_init = 
{
	/* EN                   */ TRUE,
	/* ENO                  */ TRUE,
}; /* end of __const__EL_format_local2__param_init */

/* initialization of PROGRAM status */
void EL_format_local2__init(void)
{
	const vt3_screen_initializer FARPTR p;

	/* initialize addressed variables */
	for ( p = __init_table__EL_format_local2; p->len; p ++ )
	{
		FarMemCopy(p->dst, p->src, p->len);
	}

	/* initialize local data */
	FarMemCopy(&EL_format_local2, &__const__EL_format_local2__param_init, sizeof __const__EL_format_local2__param_init);

	/* initialize function block instances */
}

/* PROGRAM execution */
void EL_format_local2__call(void)
{
	/* local variables */
	/* end of local variables */

	/* preamble: conditional execution */
	EL_format_local2.ENO = EL_format_local2.EN;
	if ( ! EL_format_local2.EN )
		return;


	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/MC2M/CPU0/SubRoutines/Diagnostics/EL_format_local2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	//    if(Format_BB){
	    if(MC2M_Formatted != 74){
	        (void)EL_format_local(0,2000,0);
	        // EL_format_local(0,2000,0);
	        // Format_BB = FALSE;
	        MC2M_Formatted = 74;
	        SaveParameter=(TRUE);
	        //Total_Odometer_Low = (UINT) TotalOdometer_d; 
	        //Total_Odometer_High = (UINT) (TotalOdometer_d >> 16);
	    }
	        Total_Odometer_Low = (UINT) TotalOdometer_d; 
	        Total_Odometer_High = (UINT) (TotalOdometer_d >> 16);
	}

	/* end of PROGRAM body */
}


#pragma CONST_SEG DEFAULT
#pragma DATA_SEG DEFAULT

#endif /* INCLUDE__VT3_POU__EL_FORMAT_LOCAL2_C */

/* end of file */
