/* device:       /project/MC2M/CPU0 */
/* device model: MC2M_2CPU\CPU0 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_LANG_H
#define INCLUDE__VT3_LANG_H

#include "vt3_base.h"

#pragma CONST_SEG CSEG VT3_STRINGS
#pragma DATA_SEG DSEG BANKED_RAM

/* the languages */
#define LANGUAGE_TURKCE                   (0)
#define LANGUAGE_ENGLISH                  (1)
#define LANGUAGE_ARABIC                   (2)
#define VT3_LANGUAGE_COUNT                (3)

/* the string indexes */
#define IDS_MEDIUM_PRIORITY               (0)
#define IDS_HIGH_PRIORITY                 (1)
#define IDS_GLOBAL_SPN                    (2)
#define IDS_GLOBAL_FMI                    (3)
#define IDS_SOLUTION_1                    (4)
#define IDS_LOW_PRIORITY                  (5)
#define IDS_INFO_0                        (6)
#define IDS_INFO_1                        (7)
#define IDS_INFO_2                        (8)
#define IDS_INFO_3                        (9)
#define IDS_INFO_4                        (10)
#define IDS_INFO_5                        (11)
#define IDS_INFO_6                        (12)
#define IDS_INFO_7                        (13)
#define IDS_INFO_8                        (14)
#define IDS_INFO_9                        (15)
#define IDS_INFO_10                       (16)
#define IDS_INFO_11                       (17)
#define IDS_INFO_12                       (18)
#define IDS_INFO_13                       (19)
#define IDS_INFO_14                       (20)
#define IDS_INFO_15                       (21)
#define IDS_INFO_16                       (22)
#define IDS_INFO_17                       (23)
#define IDS_INFO_18                       (24)
#define IDS_INFO_19                       (25)
#define IDS_INFO_20                       (26)
#define IDS_INFO_21                       (27)
#define IDS_INFO_22                       (28)
#define IDS_INFO_23                       (29)
#define IDS_INFO_24                       (30)
#define IDS_INFO_25                       (31)
#define IDS_INFO_26                       (32)
#define IDS_GEAR_0                        (33)
#define IDS_GEAR_1                        (34)
#define IDS_GEAR_2                        (35)
#define IDS_GEAR_3                        (36)
#define IDS_GEAR_4                        (37)
#define IDS_GEAR_5                        (38)
#define IDS_GEAR_6                        (39)
#define IDS_GEAR_7                        (40)
#define IDS_GEAR_8                        (41)
#define IDS_GEAR_9                        (42)
#define IDS_GEAR_10                       (43)
#define IDS_TANK_M                        (44)
#define IDS_TANK_A                        (45)
#define IDS_TEXT0                         (46)
#define IDS_TEXT1                         (47)
#define IDS_TEXT2                         (48)
#define IDS_TEXT3                         (49)
#define IDS_TEXT4                         (50)
#define IDS_TEXT5                         (51)
#define IDS_TEXT6                         (52)
#define IDS_ONEMLI                        (53)
#define SPN_1                             (54)
#define FMI_1                             (55)
#define GROUP_1                           (56)
#define GIGA_TEXT0                        (57)
#define GIGA_TEXT1                        (58)
#define GIGA_TEXT2                        (59)
#define GIGA_TEXT3                        (60)
#define GIGA_TEXT4                        (61)
#define GIGA_TEXT5                        (62)
#define GIGA_TEXT6                        (63)
#define GIGA_TEXT7                        (64)
#define GIGA_TEXT8                        (65)
#define GIGA_TEXT9                        (66)
#define GIGA_TEXT10                       (67)
#define GIGA_ST_TEXT0                     (68)
#define GIGA_ST_TEXT1                     (69)
#define GIGA_ST_TEXT2                     (70)
#define IDS_TEXT7                         (71)
#define IDS_TEXT8                         (72)
#define IDS_TEXT9                         (73)
#define IDS_TEXT10                        (74)
#define IDS_TEXT11                        (75)
#define IDS_TEXT12                        (76)
#define IDS_TEXT13                        (77)
#define IDS_TEXT14                        (78)
#define IDS_TEXT15                        (79)
#define IDS_TEXT16                        (80)
#define IDS_TEXT17                        (81)
#define IDS_TEXT18                        (82)
#define IDS_TEXT19                        (83)
#define IDS_TEXT20                        (84)
#define IDS_TEXT21                        (85)
#define IDS_TEXT22                        (86)
#define IDS_TEXT23                        (87)
#define IDS_TEXT24                        (88)
#define IDS_TEXT25                        (89)
#define IDS_TEXT26                        (90)
#define IDS_TEXT27                        (91)
#define IDS_TEXT28                        (92)
#define IDS_TEXT29                        (93)
#define IDS_TEXT30                        (94)
#define IDS_TEXT31                        (95)
#define IDS_TEXT32                        (96)
#define IDS_TEXT33                        (97)
#define IDS_TEXT34                        (98)
#define IDS_TEXT35                        (99)
#define IDS_TEXT36                        (100)
#define IDS_TEXT37                        (101)
#define IDS_TEXT38                        (102)
#define IDS_TEXT39                        (103)
#define IDS_TEXT40                        (104)
#define IDS_TEXT41                        (105)
#define IDS_TEXT42                        (106)
#define IDS_TEXT43                        (107)
#define IDS_TEXT44                        (108)
#define IDS_TEXT45                        (109)
#define IDS_TEXT46                        (110)
#define IDS_TEXT47                        (111)
#define IDS_TEXT48                        (112)
#define IDS_TEXT49                        (113)
#define IDS_TEXT50                        (114)
#define IDS_TEXT51                        (115)
#define IDS_TEXT52                        (116)
#define IDS_TEXT53                        (117)
#define IDS_TEXT54                        (118)
#define IDS_TEXT55                        (119)
#define IDS_TEXT56                        (120)
#define IDS_TEXT_NMSGUI_0                 (121)
#define IDS_TEXT_NMSGUI_1                 (122)
#define IDS_TEXT_NMSGUI_2                 (123)
#define IDS_TEXT_NMSGUI_3                 (124)
#define IDS_TEXT_NMSGUI_4                 (125)
#define IDS_TEXT_NMSGUI_5                 (126)
#define IDS_TEXT_NMSGUI_6                 (127)
#define IDS_TEXT_NMSGUI_7                 (128)
#define IDS_TEXT_NMSGUI_8                 (129)
#define IDS_TEXT_NMSGUI_9                 (130)
#define IDS_TEXT_NMSGUI_10                (131)
#define IDS_TEXT_NMSGUI_11                (132)
#define IDS_TEXT_NMSGUI_12                (133)
#define IDS_TEXT_NMSGUI_13                (134)
#define VT3_TRANSLATION_STRINGS           (135)

/* translation function */
const FAR char FARPTR const vt3_translate(
	unsigned int ids, 
	unsigned int lang);

#pragma CONST_SEG DEFAULT
#pragma DATA_SEG DEFAULT


#endif /* INCLUDE__VT3_LANG_H */

/* end of file */
