/* device:       /project/GIGA */
/* device model: GIGA_05600005_01 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SCREEN4_C
#define INCLUDE__VT3_EVENT__SCREEN4_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Screen4.h"
#include "vt3_Event__Screen4.h"
#include "vt3_extra.h"

/* define the names of the indicators */

/* define the names of the indicators */

/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for screen: /project/GIGA/Screens/screen_4 */
void vt3_event_ind_screen_4(BYTE event)
{
	{
		/* literal constants used in ST */
		/* end of literals */

		/* statements */
		switch ( (SubMenuVar2) )
		{
		case 0:
			vt3_screen_union.screen_4.simple_text_07.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_08.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_09.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_10.color = (INT)((SINT)4);
			GIGAMenuVar03 = (USINT)((SINT)0);
			break;
		case 1:
			vt3_screen_union.screen_4.simple_text_07.color = (INT)((INT)250);
			vt3_screen_union.screen_4.simple_text_08.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_09.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_10.color = (INT)((SINT)4);
			GIGAMenuVar03 = (USINT)((SINT)0);
			break;
		case 2:
			vt3_screen_union.screen_4.simple_text_07.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_08.color = (INT)((INT)250);
			vt3_screen_union.screen_4.simple_text_09.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_10.color = (INT)((SINT)4);
			GIGAMenuVar03 = (USINT)((SINT)0);
			break;
		case 3:
			vt3_screen_union.screen_4.simple_text_07.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_08.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_09.color = (INT)((INT)250);
			vt3_screen_union.screen_4.simple_text_10.color = (INT)((SINT)4);
			GIGAMenuVar03 = (USINT)((SINT)0);
			break;
		case 4:
			vt3_screen_union.screen_4.simple_text_07.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_08.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_09.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_10.color = (INT)((INT)250);
			GIGAMenuVar03 = (USINT)((SINT)0);
			break;
		case 5:
			vt3_screen_union.screen_4.simple_text_07.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_08.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_09.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_10.color = (INT)((SINT)4);
			GIGAMenuVar03 = (USINT)((SINT)0);
			break;
		case 6:
			vt3_screen_union.screen_4.simple_text_07.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_08.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_09.color = (INT)((SINT)4);
			vt3_screen_union.screen_4.simple_text_10.color = (INT)((SINT)4);
			GIGAMenuVar03 = (USINT)((SINT)1);
			break;
		default:
			;
		}
		

		/* end of statements */

		/* POU exit point */
		goto __return__;
	__return__:
		return;

	}


} /* end of event code for indicator: screen_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/simple_text_07 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_simple_text_07(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(PanelBrightHUptOnScreen);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/simple_text_07
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_07 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/simple_text_08 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_simple_text_08(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(PanelBrightLUptOnScreen);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/simple_text_08
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_08 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/simple_text_09 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_simple_text_09(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(ScreenBrightHUptOnScreen);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/simple_text_09
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_09 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/simple_text_10 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_simple_text_10(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(ScreenBrightLUptOnScreen);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/simple_text_10
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_10 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/Return_Text_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_4_Return_Text_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar03));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/Return_Text_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Return_Text_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/Date_Time_Caption_Text 
 * runs every 0ms
 */
void vt3_event_ind_screen_4_Date_Time_Caption_Text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar01));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/Date_Time_Caption_Text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Date_Time_Caption_Text */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/Return_Text 
 * runs every 0ms
 */
void vt3_event_ind_screen_4_Return_Text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar02));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/Return_Text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Return_Text */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext_3_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (EQ_BYTE_2((SubMenuVar2),
		((SINT)1)));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext_2_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (EQ_BYTE_2((SubMenuVar2),
		((SINT)2)));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext_2_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext_2_2_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (EQ_BYTE_2((SubMenuVar2),
		((SINT)3)));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext_2_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext_2_2_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext_2_2_2_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (EQ_BYTE_2((SubMenuVar2),
		((SINT)4)));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext_2_2_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_2_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_4/multitext_2_2_2_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_4_multitext_2_2_2_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (EQ_BYTE_2((SubMenuVar2),
		((SINT)5)));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_4/multitext_2_2_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_2_2_3 */


#endif /* INCLUDE__VT3_EVENT__SCREEN4_C */

/* end of file */
