/* device:       /project/GIGA */
/* device model: GIGA_05600005_01 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SCREEN1_C
#define INCLUDE__VT3_EVENT__SCREEN1_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Screen1.h"
#include "vt3_Event__Screen1.h"
#include "vt3_extra.h"

/* define the names of the indicators */

/* define the names of the indicators */

/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for screen: /project/GIGA/Screens/screen_1 */
void vt3_event_ind_screen_1(BYTE event)
{

} /* end of event code for indicator: screen_1 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multitext_1 
 * runs every 0ms
 */
void vt3_event_ind_screen_1_multitext_1(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((InfoNo5));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multitext_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_1 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multitext_1_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_1_multitext_1_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((InfoNo6));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multitext_1_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_1_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(DateOnScreen);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(TimeOnScreen);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multibitmap_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multibitmap_2(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multibitmap_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multibitmap_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multibitmap_2_2(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multibitmap_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multibitmap_2_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multibitmap_2_3(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multibitmap_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap_2_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/number_2_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_number_2_3_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = (VT3_ATOMIC_READ_UDINT(ScreenOdometer));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/number_2_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: number_2_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(2) FAR _str = { 2, 2, "Km" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text */


/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressGauge 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressGauge(
	BYTE event, 
	vt3_indicator_GaugeBar FARPTR ind)
{
	ind->currentValue = ((GIGA_ServiceBrake1));


} /* end of event code for indicator: FBPressGauge */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_ServiceBrake1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValueUnit 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValueUnit(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(3) FAR _str = { 3, 3, "bar" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValueUnit
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValueUnit */


/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressGauge_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressGauge_2(
	BYTE event, 
	vt3_indicator_GaugeBar FARPTR ind)
{
	ind->currentValue = ((GIGA_ParkingBrakePressure));


} /* end of event code for indicator: FBPressGauge_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_ParkingBrakePressure));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValueUnit_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValueUnit_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(3) FAR _str = { 3, 3, "bar" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValueUnit_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValueUnit_2 */


/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressGauge_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressGauge_3(
	BYTE event, 
	vt3_indicator_GaugeBar FARPTR ind)
{
	ind->currentValue = ((GIGA_ServiceBrake2));


} /* end of event code for indicator: FBPressGauge_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue_3(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_ServiceBrake2));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValueUnit_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValueUnit_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(3) FAR _str = { 3, 3, "bar" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValueUnit_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValueUnit_3 */


/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressGauge_4 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressGauge_4(
	BYTE event, 
	vt3_indicator_GaugeBar FARPTR ind)
{
	ind->currentValue = ((GIGA_AccessoryPressure));


} /* end of event code for indicator: FBPressGauge_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue_4 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue_4(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_AccessoryPressure));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValueUnit_4 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValueUnit_4(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(3) FAR _str = { 3, 3, "bar" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValueUnit_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValueUnit_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multibitmap_2_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multibitmap_2_3_2(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multibitmap_2_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap_2_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multibitmap_2_3_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multibitmap_2_3_2_2(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multibitmap_2_3_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap_2_3_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multibitmap_2_3_2_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multibitmap_2_3_2_3(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multibitmap_2_3_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap_2_3_2_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/number_2_3_2_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_number_2_3_2_3(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((MC2M_TERA_BatteryLevel));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/number_2_3_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: number_2_3_2_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/EngineHour 
 * runs every 0ms
 */
void vt3_event_ind_screen_1_EngineHour(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = UDINT_TO_STRING(VT3_ATOMIC_READ_UDINT(MC2M_TERA_DIAG_TotalEngineHours));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/EngineHour
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: EngineHour */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multitext_5 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multitext_5(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (ADD_SINT((MC2M_TERA_CurrentGear),
		((SINT)1)));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multitext_5
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_5 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_3_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_3_3_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "V" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_3_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multitext_6 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multitext_6(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multitext_6
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_6 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multitext_6_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multitext_6_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multitext_6_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_6_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multitext_6_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_multitext_6_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multitext_6_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_6_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/multitext_7 
 * runs every 1000ms
 */
void vt3_event_ind_screen_1_multitext_7(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/multitext_7
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_7 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue_3_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_HyraulicLevel));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue_3_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue_3_2_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_HyraulicTemp));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue_3_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_3_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "C" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2_3_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(3) FAR _str = { 3, 3, "kPa" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/vvrPump 
 * runs every 1000ms
 */
void vt3_event_ind_screen_1_vvrPump(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_RadiatorTemp));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/vvrPump
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: vvrPump */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2_3_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2_3_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(10) FAR _str = { 10, 10, "C Radiator" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2_3_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2_3_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2_3_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2_3_3_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(7) FAR _str = { 7, 7, "Trigger" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2_3_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2_3_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue_3_2_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue_3_2_3(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_VVRPumpTrigger));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue_3_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_3_2_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/vvrPump_2 
 * runs every 1000ms
 */
void vt3_event_ind_screen_1_vvrPump_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_CACTemp));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/vvrPump_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: vvrPump_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2_3_3_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2_3_3_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(5) FAR _str = { 5, 5, "C CAC" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2_3_3_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2_3_3_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/vvrPump_3 
 * runs every 1000ms
 */
void vt3_event_ind_screen_1_vvrPump_3(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_VVRPump));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/vvrPump_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: vvrPump_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/simple_text_2_3_3_4 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_simple_text_2_3_3_4(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "%" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/simple_text_2_3_3_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2_3_3_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_1/FBPressValue_3_2_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_1_FBPressValue_3_2_2_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((MC2M_TERA_HTempInputFiltered));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_1/FBPressValue_3_2_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_3_2_2_2 */


#endif /* INCLUDE__VT3_EVENT__SCREEN1_C */

/* end of file */
