/* device:       /project/GIGA */
/* device model: GIGA_05600005_01 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SCREEN5_C
#define INCLUDE__VT3_EVENT__SCREEN5_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Screen5.h"
#include "vt3_Event__Screen5.h"
#include "vt3_extra.h"

/* define the names of the indicators */

/* define the names of the indicators */

/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for screen: /project/GIGA/Screens/screen_5 */
void vt3_event_ind_screen_5(BYTE event)
{

} /* end of event code for indicator: screen_5 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_3_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_5_multitext_3_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar01));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(DiagMessage01);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(3) FAR _str = { 3, 3, "SPN" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_4 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_4(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(3) FAR _str = { 3, 3, "FMI" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_3_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(DiagMessage03);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_3_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_3_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(DiagMessage05);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_3_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_3_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_3_4 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_3_4(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(DiagMessage02);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_3_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_3_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_3_5 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_3_5(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(DiagMessage04);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_3_5
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_3_5 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_3_6 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_3_6(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = (PSTRING)&(DiagMessage06);

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_3_6
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_3_6 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/EngineHour 
 * runs every 0ms
 */
void vt3_event_ind_screen_5_EngineHour(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = UDINT_TO_STRING(DIV_UDINT(VT3_ATOMIC_READ_UDINT(GIGAOdometerBackup),
			((INT)1000)));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/EngineHour
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: EngineHour */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_7 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_7(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(2) FAR _str = { 2, 2, "Km" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_7
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_7 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/FBPressValue_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_FBPressValue_3(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_HyraulicLevel));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/FBPressValue_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_7_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_7_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(5) FAR _str = { 5, 5, "/ 100" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_7_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_7_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_7_2_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_7_2_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "C" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_7_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_7_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/FBPressValue_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_FBPressValue_3_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((GIGA_HyraulicTemp));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/FBPressValue_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: FBPressValue_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/EngineHour_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_5_EngineHour_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = UDINT_TO_STRING(VT3_ATOMIC_READ_UDINT(MC2M_TERA_DIAG_TotalEngineHours));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/EngineHour_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: EngineHour_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_7_3 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_7_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(2) FAR _str = { 2, 2, "Sa" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_7_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_7_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/EngineHour_2_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_5_EngineHour_2_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = UDINT_TO_STRING(VT3_ATOMIC_READ_UDINT(MC2M_TERA_DIAG_TotalEngineHours_Old));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/EngineHour_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: EngineHour_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/simple_text_3_7_3_2 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_simple_text_3_7_3_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(2) FAR _str = { 2, 2, "Sa" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/simple_text_3_7_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_3_7_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext 
 * runs every 200ms
 */
void vt3_event_ind_screen_5_multitext(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2_2 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2_3 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2_4 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2_4(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2_4_2 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2_4_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2_4_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_4_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2_4_3 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2_4_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2_4_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_4_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2_4_4 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2_4_4(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2_4_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_4_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/multitext_2_4_5 
 * runs every 1000ms
 */
void vt3_event_ind_screen_5_multitext_2_4_5(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/multitext_2_4_5
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_2_4_5 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_5/EngineHour_2_3 
 * runs every 0ms
 */
void vt3_event_ind_screen_5_EngineHour_2_3(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	ind->currentValue = UINT_TO_STRING((MC2M_TERA_BackDoorTest_Prd));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_5/EngineHour_2_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: EngineHour_2_3 */


#endif /* INCLUDE__VT3_EVENT__SCREEN5_C */

/* end of file */
