/* device:       /project/GIGA */
/* device model: GIGA_05600005_01 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SCREEN6_C
#define INCLUDE__VT3_EVENT__SCREEN6_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Screen6.h"
#include "vt3_Event__Screen6.h"
#include "vt3_extra.h"

/* define the names of the indicators */

/* define the names of the indicators */

/* suppress HC12 specific warnings */
#pragma MESSAGE DISABLE C5909 // Assignment in condition
#pragma MESSAGE DISABLE C5918 // Removed dead goto
#pragma MESSAGE DISABLE C5917 // Removed dead assignment
#pragma MESSAGE DISABLE C5660 // Removed dead code
#pragma MESSAGE DISABLE C1420 // Result of function-call is ignored
#pragma MESSAGE DISABLE C4002 // Result not used

/* timer event handler for screen: /project/GIGA/Screens/screen_6 */
void vt3_event_ind_screen_6(BYTE event)
{

} /* end of event code for indicator: screen_6 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multibitmap 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multibitmap(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((GIGAMenuNo));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multibitmap
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar01));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext_3 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar02));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext_3_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext_3_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar05));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext_3_3 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext_3_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar03));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext_3_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_3_3 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext_3_3_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext_3_3_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar04));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext_3_3_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_3_3_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext_4 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext_4(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar06));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_4 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext_4_2 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext_4_2(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar07));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext_4_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_4_2 */


/* timer event handler for indicator: /project/GIGA/Screens/screen_6/multitext_4_3 
 * runs every 0ms
 */
void vt3_event_ind_screen_6_multitext_4_3(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((GIGAMenuVar08));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/GIGA/Screens/screen_6/multitext_4_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multitext_4_3 */


#endif /* INCLUDE__VT3_EVENT__SCREEN6_C */

/* end of file */
