
     
    GIGASpeed := 0;
    GIGAEngineSpeed  := 0;
    GIGAFuelLevel := 0;
    GIGAEngineTempValue := 0;
    GIGAEngineOilPressure  := 0;
    GIGATransOilTemperature  := 0;
    Backlight :=0;
    BacklightScreen:=0;
    GIGAGaugeOverride0 := 0;    
    GIGAGaugeOverride1 := 0;    
    GIGAGaugeOverride2 := 0;    
    GIGAGaugeOverride3 := 0;    
    GIGAGaugeOverride4 := 0;    
    GIGAGaugeOverride5 := 0;    
    GIGABarGaugeOverride := 0;    
    led_tmp := FALSE;

    L10_Difflock_Dropbox := FALSE;    
    L11_Difflock_Front := FALSE;
    L12_Difflock_Rear := FALSE;